SunnySuite/Sunny.jl

examples/reproduce_testcases.jl
src/Anisotropies.jl
src/Ewald.jl
src/FourierAccel.jl
src/Hamiltonian.jl
src/Integrators.jl
src/Interactions.jl
src/Metropolis.jl
src/PairInteractions.jl
src/Plotting.jl
src/ReplicaExchangeMC.jl
src/StructureFactors.jl
src/Sunny.jl
src/Systems.jl
src/Util.jl
src/WangLandau/WangLandau.jl
test/runtests.jl
test/test_dynamics.jl
test/test_ewald.jl
test/test_fourier.jl
test/test_langevin.jl
test/test_metropolis.jl
test/test_pair_interactions.jl
test/test_spin_scaling.jl
test/test_units.jl

The SU(N) integration was first merged into `refactor-for-sun`. This PR is to merge `refactor-for-sun` into `main`.

Refactor for sun

---

src/Integrators.jl
src/Metropolis.jl

This is just a couple of additional methods and fixes for `rand!` and `get_system`. The changes are necessary to make the code in the tutorial notebook cleaner.  I will go ahead and merge.

additional wrapper functions for LangevinSampler

---

src/Integrators.jl
src/StructureFactors.jl

Just some quick fixes to the indexing in StructureFactors.jl. In particular, forgot to update the indices for the creation of the FFT plan.

Indexing refactor bugfixes

---

src/Sunny.jl
src/SunnyGfx/CrystalViewer.jl
src/SunnyGfx/SunnyGfx.jl
src/SunnyGfx/assets/crystal_viewer.js

Cleaning up some of the SunnyGfx code. Now includes a more convenient way to open a browser. Would be nice to test on Linux and Windows before merging.

Graphics update

---

Project.toml
test/Project.toml
test/runtests.jl
test/test_dynamics.jl
test/test_ewald.jl
test/test_fourier.jl
test/test_langevin.jl
test/test_lattice.jl
test/test_metropolis.jl
test/test_pair_interactions.jl
test/test_shared.jl
test/test_spin_scaling.jl
test/test_structure_factors.jl
test/test_symmetry.jl
test/test_units.jl

Convert to TestItemRunner

---

src/Lattice.jl
src/Systems.jl

This should resolve #35 . I did not add tests because I'm expecting a big refactor to Lattice.

Fix extend_periodically

---

NEWS.md
docs/src/library.md
src/Sunny.jl
src/Symmetry/Anisotropy.jl
src/Symmetry/Bond.jl
src/Symmetry/LocalOperators.jl
src/Symmetry/Printing.jl
test/test_symmetry.jl

This adds a named parameter `N` to the function `print_anisotropy_as_stevens()`. Also includes various cleanups, especially improvements to printing of polynomials.

Print anisotropy as Stevens for given N

---

src/PairInteractions.jl

This bug was discovered and fixed by Chaebin Kim.

Fix DM interaction

---

src/Sunny.jl
src/System/PairExchange.jl
src/System/System.jl
test/test_resize.jl

Also extend `symmetry_equivalent_bonds` to include offset information

New function, `remove_periodicity`

---

src/SpinWaveTheory/SWTCalculations.jl
src/SpinWaveTheory/SpinWaveTheory.jl

Now the dipole mode only involves SO(3) rotations. It will become consistent with two notes in preparation.

Let swt-dipole mode involve SO(3) rotation only

---

src/Symmetry/SymmetryAnalysis.jl

Fixes https://github.com/SunnySuite/Sunny.jl/issues/106.

Bond is always symmetry equivalent to its reverse

---

docs/Project.toml
docs/make.jl
examples/fei2_classical.jl

This is a work in progress. It is mostly a recycling of the second half of the old tutorial.

Finite Temperature FeI2 Example

---

docs/make.jl
examples/fei2_classical.jl
examples/fei2_tutorial.jl
examples/longer_examples/CoRh2O4-tutorial.jl
examples/longer_examples/MgCr2O4-tutorial.jl
examples/powder_averaging.jl

Addresses the first part of https://github.com/SunnySuite/Sunny.jl/issues/144
Upcoming Makie 0.20 will fix the resolution issues across GLMakie/WGLMakie and different machines.
We can revisit WGLMakie arrow colors later.
Lines ending in `#hide` do show up in the notebook builds, but we can address making them prettier later.

Build Jupyter notebooks and link from docs

---

docs/make.jl

Attempt to link notebooks

---

docs/make.jl

Also add links from each example doc page.

Generate example script files

---

src/Symmetry/SymmetryAnalysis.jl

This should actually fix https://github.com/SunnySuite/Sunny.jl/issues/106

Remove faulty P1 logic

---

docs/src/versions.md
examples/extra/heisenberg_animation.jl
ext/PlottingExt.jl
src/Intensities/LinearSpinWaveIntensities.jl
src/SpinWaveTheory/SpinWaveTheory.jl

This includes all helper functions and hooks needed to make the eigenmode viewer work.

Eigenmode viewer hooks

---

docs/Project.toml
docs/make.jl

This is just a test of the doc build system.

Separate build for contributed docs

---

src/Reshaping.jl
src/SpinWaveTheory/SpinWaveTheory.jl
src/Symmetry/Crystal.jl
src/System/OnsiteCoupling.jl
src/System/PairExchange.jl
src/System/System.jl

This feature will support the upcoming LSWT-KPM capability developed by @hlane33.

Allow reshaping an inhomogeneous system to a single unit cell

---

Project.toml
ext/PlottingExt.jl
src/Sunny.jl
src/Symmetry/Crystal.jl
test/Project.toml
test/test_aqua.jl

Add Aqua to unit tests. Also remove outdated dependencies.

Add Aqua tests

---

docs/make.jl
docs/src/versions.md
ext/PlottingExt.jl

Addresses https://github.com/SunnySuite/Sunny.jl/issues/209.

Warn if WGLMakie detected

---

.github/DocCleanup.yml

Based on https://documenter.juliadocs.org/stable/man/hosting/#Cleaning-up-gh-pages

Add DocCleanup.yml action

---

docs/src/versions.md
ext/PlottingExt.jl
src/Operators/Rotation.jl
src/Reshaping.jl
src/Symmetry/AllowedAnisotropy.jl
src/Symmetry/AllowedCouplings.jl
src/Symmetry/Printing.jl
src/Symmetry/SymOp.jl
src/Symmetry/SymmetryAnalysis.jl
src/System/PairExchange.jl
src/System/System.jl

`view_crystal` now accepts a `System`, and will show exchange interactions graphically.

Enhancements to `view_crystal`

---

Project.toml
ext/GLMakiePrecompilesExt.jl
ext/PlottingExt.jl
ext/WGLMakiePrecompilesExt.jl
src/Sunny.jl

Precompile `view_crystal` according to the specific Makie backend that is loaded.

Precompiles for Makie backends

---

src/Intensities/Interpolation.jl

This never got updated when adding `formula` and confused a user 😅

Make `instant_intensities_interpolated` docstring in line with `intensities_interpolated`

---

src/System/Interactions.jl
src/System/System.jl

A stopgap until https://github.com/SunnySuite/Sunny.jl/pull/247 is merged in Sunny 0.6.

Document magnetic moment sign error

---

src/System/SpinInfo.jl

Informative error message regarding zero-spin

---

examples/03_LLD_CoRh2O4.jl
examples/04_GSD_FeI2.jl
examples/spinw_tutorials/SW04_Frustrated_square.jl
examples/spinw_tutorials/SW05_Simple_kagome_FM.jl
examples/spinw_tutorials/SW06_Complex_kagome_FM.jl
examples/spinw_tutorials/SW07_k0_kagome_AFM.jl
examples/spinw_tutorials/SW08_sqrt3_kagome_AFM.jl
examples/spinw_tutorials/SW09_k0_kagome_AFM_DM.jl
examples/spinw_tutorials/SW10_Energy_cut.jl
examples/spinw_tutorials/SW11_La2CuO4.jl
examples/spinw_tutorials/SW15_Ba3NbFe3Si2O14.jl
ext/PlottingExt.jl

Also fixes bugs in `plot_intensities` inferred color range, and supports plotting of an instant intensities along a path.

Add SpinW tutorials 9, 10, 11

---

docs/make.jl
test/test_lswt.jl

Reintroduces the contributed docs to build.

Uncomment contributed build commands

---

Project.toml
README.md
docs/src/versions.md
examples/03_LSWT_SU3_FeI2.jl

Also require HCubature 1.7.0 to ensure thread safety.

Update README and docs

---

docs/src/versions.md
src/Optimization.jl
test/test_energy_consistency.jl
test/test_optimization.jl

Properly handle vacancies with `minimize_energy!`

---

docs/make.jl

Add Sunny version check to generated scripts

---

docs/src/why.md
examples/01_LSWT_CoRh2O4.jl
examples/02_LLD_CoRh2O4.jl
examples/03_LSWT_SU3_FeI2.jl
examples/04_GSD_FeI2.jl
examples/06_CP2_Skyrmions.jl
examples/08_Momentum_Conventions.jl
examples/09_Disorder_KPM.jl
examples/spinw_tutorials/SW01_FM_Heseinberg_chain.jl
examples/spinw_tutorials/SW02_AFM_Heisenberg_chain.jl
examples/spinw_tutorials/SW03_Frustrated_chain.jl
examples/spinw_tutorials/SW04_Frustrated_square.jl
examples/spinw_tutorials/SW05_Simple_kagome_FM.jl
examples/spinw_tutorials/SW06_Complex_kagome_FM.jl
examples/spinw_tutorials/SW07_k0_kagome_AFM.jl
examples/spinw_tutorials/SW08_sqrt3_kagome_AFM.jl
examples/spinw_tutorials/SW09_k0_kagome_AFM_DM.jl
examples/spinw_tutorials/SW10_Energy_cut.jl
examples/spinw_tutorials/SW18_Distorted_kagome.jl
src/Binning/Binning.jl
src/EntangledUnits/EntangledSpinWaveTheory.jl
src/EntangledUnits/EntangledUnits.jl
src/Measurements/MeasureSpec.jl
src/Spiral/SpiralEnergy.jl
src/Symmetry/Crystal.jl
src/Symmetry/SpacegroupData.jl
src/System/OnsiteCoupling.jl

Miscellaneous cleanups

---

docs/src/versions.md
src/System/OnsiteCoupling.jl
src/System/PairExchange.jl

Error on impossible quantum spin-1/2 couplings

---

examples/08_Momentum_Conventions.jl
src/System/System.jl

Fix analytical solution for the dispersion and clarify presentation.

Revise tutorial on momentum transfer conversions
