SunnySuite/Sunny.jl

examples/PT_afm_heisenberg.jl
src/ParallelTempering.jl
src/Sunny.jl

This needs to be tuned and set up for simulations, but the basic implementation is there.

Add ParallelTempering

---

docs/src/examples.md
docs/src/index.md
examples/PT_afm_diamond.jl
examples/reproduce_testcases.jl
src/Ewald.jl
src/Hamiltonian.jl
src/Integrators.jl
src/Interactions.jl
src/Lattice.jl
src/Metropolis.jl
src/PairInteractions.jl
src/ParallelTempering.jl
src/Plotting.jl
src/StructureFactors.jl
src/Symmetry/AllowedCouplings.jl
src/Symmetry/Bond.jl
src/Symmetry/Crystal.jl
src/Symmetry/Printing.jl
src/Symmetry/SymmetryAnalysis.jl
src/Systems.jl
src/WangLandau/WangLandau.jl
test/test_ewald.jl
test/test_pair_interactions.jl

This PR removes the arbitrary-dimensionality functionality of many types throughout Sunny, as some components were effectively locking the dimensionality to 3 anyway. Additionally, 1D + 2D simulations can easily still be performed in the 3D framework, and nobody wants to do >3D simulations.
Effectively, three type parameters can be removed from many types throughout Sunny, and the dimensionality of many arrays is now fixed and statically known. This should buy us some budget for complexity when we inevitably need to add more type parameters for SU(N) simulations.
We also can remove `OnSiteQuadratic`, which only existed in the first place to dodge an awkward unknown-dimensionality problem we previously had.

Remove arbitrary-dimension lattices and systems

---

docs/src/examples.md
docs/src/internals.md
docs/src/library.md
examples/PT_afm_diamond.jl
src/Ewald.jl
src/FourierAccel.jl
src/Hamiltonian.jl
src/Interactions.jl
src/Metropolis.jl
src/PairInteractions.jl
src/ParallelTempering.jl
src/Plotting.jl
src/Sunny.jl
src/Systems.jl
test/test_ewald.jl
test/test_fourier.jl
test/test_pair_interactions.jl
test/test_units.jl

In the previous code generating pair interactions, and using them to compute energies and fields, there was a lot of difficult-to-read code which mucked around with lists of bonds living on different sublattices.
This PR attempts to consolidate all of that logic into a new (internal) type `BondTable`, which exposes simple interfaces for iterating over all bonds, the culled bonds, or just those on a certain sublattice.
An additional goal of this refactor is that a single `Vector{Bond}` is more amenable to being put on the GPU than the `Vector{Vector{Bond}}` we worked with previously. The CUDA kernels I have been working on depend on this linear layout.

Refactor bond-handling code in PairInteractions.jl into new type `BondTable`

---

examples/reproduce_testcases.jl
src/Integrators.jl
src/Interactions.jl
src/StructureFactors.jl
src/Systems.jl
test/runtests.jl
test/test_structure_factors.jl

Main changes:
1. Structure factor interface changed slightly. For `dynamic_structure_factor`, user no longer sets `meas_rate`. Instead, they may set a `omega_max`, which will determine the down sampling. Number of frequencies resolved is specified with `num_omegas` (not `dyn_meas`). `dynΔt` is now just `dt`.
2. Form factor calculations have been revised. FF information is specified with `SiteInfo`. The corrections are precomputed prior to structure factor calculations and applied after calculating magnetization.
3. Some simple tests have been added for the structure factor material, but they are very preliminary: they don't test for correctness of results, just for errors. I have them commented out for now, but I run them before pushing. They would have caught the errors I introduced …

Sf ff revisions

---

src/Hamiltonian.jl
test/test_lattice.jl
test/test_shared.jl
test/test_spin_scaling.jl

Be more careful about how we test whether a bond wraps the system. This fixes a bug Xiaojian found, and also suggested some updates to the tests on spin scaling.

Fix wrapping tests

---

src/Symmetry/Crystal.jl
test/test_symmetry.jl

Ovi Garlea reported that he was not getting the expected crystal with this code:
```julia
using Sunny
lat_vecs = lattice_vectors(13.261, 7.718, 6.278, 90.0, 90.0, 90.0);
types = ["Yb1","Yb2"];
basis_vecs = [[0,0,0], [0.266,0.25,0.997]]; # Locations of atoms as multiples of lattice vectors
Crystal(lat_vecs, basis_vecs,62;types,symprec=0.001)
```
The problem is that space group 62 could have multiple interpretations. For example, it could be any of 6 possible Hall numbers, 292...297 ( ["Setos page" has the full list](https://yseto.net/?page_id=29%3E)). These can be disambiguated with an approprate "setting" parameter. To add to the confusion, each of these settings has a different HM symbol, and Sunny was not prepared to handle it.
This PR fixes the bug, and the above code now outputs:
``` …
```

Fix issue with ambiguous crystal setting

---

src/Hamiltonian.jl
src/Integrators.jl
src/Interactions.jl
src/Symmetry/Crystal.jl
src/Systems.jl
test/test_lattice.jl

Note that `error()` throws an exception, whereas `@error` does not. Convert all instances to the former.
For consistency with the rest of the codebase, remove usages of `@warn`. Eventually we may want to replace all `println()` warning statements with `@warn`.
Additionally: Make system-wrapping interactions a warning rather than an error.

Remove uses of Logging macros

---

src/StructureFactors.jl
test/test_structure_factors.jl

This is a collection of minor revisions and bug fixes to make it easier to check sum rules. The intensities are also rescaled to match physical conventions. This makes it easier to compare results from Sunny directly with spin wave calculations.
Changes in behavior and features:
1. Accumulation of SF samples is now done with averaging, $\overline{x}_{n}= \overline{x}_{n-1}+\frac{x_{n} - \overline{x}_{n-1}}{n}$, so the intensity doesn't grow with the number of samples.
2. The Fourier transforms of the trajectories are now scaled by a factor of $\frac{1}{\sqrt{N_1N_2N_3}T}$, where $N_i$ is the dimension of the lattice along lattice vector $i$, and $T$ is the number of time steps. The resulting intensities are now comparable to what would be given by spin wave calculations. In particular, if …

SF intensity and sum rule revisions

---

Project.toml
src/Integrators.jl
src/Symmetry/LocalOperators.jl
test/test_dynamics.jl
test/test_spin_scaling.jl
test/test_symmetry.jl

Removes the need to keep the spin matrices in memory for N > 5. Instead adds a function called `add_dipolar_field!(op::Array{ComplexF64, 2}, B::Vec3` which adds `B ⋅ S` to `op` by constructing the relevant matrix elements of the spin matrices on the fly. For N=6 this is marginally faster than keeping the matrices stored (3-5%). I also tried N=10, where it was about 10% faster than storing the matrices. So it seems like this is a reasonable approach to dealing with the N > 5 case, at least for now.
I added a test that ensures this function does what it should. I also added an `N=6` case to the spin rescaling tests, so that the `N > 5` case is at least run during routine testing.

Large N integrator fix

---

src/ReplicaExchangeMC.jl
src/System/Ewald.jl
src/System/Interactions.jl
src/System/System.jl
test/mc_tests/REMC_H_Ising2D.jl
test/test_energy_consistency.jl

Julia developers Gabriel Baraldi and Jameson Nash pointed out that the use of `deepcopy` can be memory unsafe, especially when used in combination with C datastructures. It appears this was the source of intermittent segfault behavior observed when calling FFTW. (Perhaps the problem was deep-copying an FFTW plan, or perhaps it was some other memory corruption.)
This PR replaces all calls to `deepcopy` with custom clone functions that  perform ordinary `copy` operations on mutable arrays. Hopefully resolves https://github.com/SunnySuite/Sunny.jl/issues/65, originally reported in https://github.com/JuliaLang/julia/issues/48722 .

Avoid all use of `deepcopy`

---

src/SpinWave/SWUtil.jl
src/SpinWave/SpinWave.jl
src/Sunny.jl
test/test_lswt.jl

This PR adds the SU(N) linear spin-wave theory features to Sunny. The `:SUN` and `: dipole` modes are supported. But the `:large_S` mode is not supported yet. Moreover, the `biquad` interactions are not supported.

Add SU(N) LSWT to Sunny

---

src/Integrators.jl
src/StructureFactors/BasisReduction.jl
src/StructureFactors/SampleGeneration.jl
src/StructureFactors/StructureFactors.jl

@kbarros , in anticipation of working on inverse problem (= approx 10^6 x forwards problem), I've made a few performance tweaks, mainly focused on making the memory allocations scale better (no GC anymore during long integrations 🎉).
These are mainly for my use but if they look useful enough for Sunny proper then I'm happy to make any style changes + squash the commits if needed.
Before:
After:

Performance enhancements for inverse problem

---

src/Sunny.jl
src/Symmetry/CartesianIndicesShifted.jl
src/System/Interactions.jl
src/System/System.jl

Uses Kip's CartesianIndicesShifted to efficiently implement periodic boundary conditions. Also accelerates `energy_aux` and allows the interactions to use site indices instead of cell+sublattice (if someone were to add an interaction in the future, this is the nicer way for them to write their code in the first place)

Accelerate force calculation

---

docs/make.jl
examples/binning_tutorial.jl
examples/fei2_tutorial.jl
examples/powder_averaging.jl
src/StructureFactors/DataRetrieval.jl
src/StructureFactors/PowderAveraging.jl
src/Sunny.jl

This isn't finished/polished yet (opening this PR to track progress).
This is the alternative interface to `intensities` which is designed to more closely align with what Mantid/Horace output. In particular, the new type `BinningParameters` is supposed to be isomorphic to the data Mantid uses to describe an "MDHistoWorkspace".
Example usage:
```julia
params = Sunny.one_dimensional_cut_binning_parameters(sf,[0,1,0],[1/2,0,0],30,0.3)
display(params)
sunHist,sunCounts = Sunny.binned_histogram(sf,params,Sunny.DipoleFactor(sf),kT,formfactors)
mx = Sunny.axes_bincenters(params)
fig3 = Plots.heatmap(mx[1],mx[4],sunCounts[:,1,1,:]')
logIntensity = log10.(sunHist[:,1,1,:]' ./ sunCounts[:,1,1,:]')
fig4 = Plots.heatmap(mx[1],mx[4],logIntensity;ylabel="E (meV)",color=cgrad(:viridis,scale = :lin,rev = …
```

Add `binned_histogram`

---

docs/src/versions.md
src/Integrators.jl
src/Reshaping.jl
src/SpinWaveTheory/SWTCalculations.jl
src/SpinWaveTheory/SpinWaveTheory.jl
src/Sunny.jl
src/Symmetry/AllowedCouplings.jl
src/System/Interactions.jl
src/System/OnsiteCoupling.jl
src/System/PairExchange.jl
src/System/SingleIonAnisotropy.jl
src/System/System.jl
src/System/Types.jl
test/shared.jl
test/test_energy_consistency.jl
test/test_lswt.jl

Internal cleanups to unify treatment of pair couplings. In particular, each atom now stores only a single list of PairCouplings, which may contain bilinear (scalar or matrix) and biquadratic (scalar-only) exchange.
The function `set_biquadratic!` has been removed. Instead, call `set_exchange!` with the keyword argument `biquad`.
The changes to the internal datastructures will require updates to LSWT, which should also be incorporated into the branches of @Hao-Phys and @hlane33.

PairCoupling refactors

---

docs/make.jl

Documenter:
Literate:
This is a PR because it's technically a super big change to how the docs are created. I don't think there are any bad side effects (the docs build OK locally) but maybe this breaks the CI somehow?

Switch docs execution from Literate to Documenter

---

src/Integrators.jl
src/Optimization.jl
src/System/Ewald.jl
src/System/Interactions.jl
test/test_optimization.jl

This should give a general way to optimize spin configurations to minimize energy. Works in both `:dipole` and `:SUN` modes. It relies on `Optim.jl` and defaults to LBFGS.
The intended use is just the touching up of spin configurations near the ground state. The function for this is `minimize_energy_touchup!(sys)`. It just runs for a maximum of 40 iterations and gives a warning if the optimizer hasn't converged.
There's also a function `minimize_energy!(sys)`, which seems to work for random initial configurations. It checks whether any of the quasi-stereographic coordinates has "wandered too far." If so, it halts the optimization, reparameterizes the coherent states, and starts it again.
It seems to be sufficiently fast for small unit cells.
All the functions called inside the …

Optimization of spin configurations (dipoles and coherents)

---

src/Operators/Symbolic.jl
src/Reshaping.jl
src/SunnyGfx/SunnyGfx.jl
src/Symmetry/AllowedAnisotropy.jl
src/Symmetry/Crystal.jl
src/Symmetry/Parsing.jl
src/Symmetry/Printing.jl
src/System/Interactions.jl
src/System/OnsiteCoupling.jl
src/System/PairExchange.jl

**UPDATED**
Only the first 5 site or pair coupling override warnings will be printed to the terminal. After that, the warnings will be suppressed.
Convert some `println` statements to `Logging.@info` and `@warn` statements. This is appropriate for providing a warning that the user wasn't expecting. Some functions, of the form `print_*` explicitly promise to print something, and here the `println()` statements seem appropriate.

Use Logging for info and warning printouts

---

src/System/OnsiteCoupling.jl
src/System/PairExchange.jl

This fixes https://github.com/SunnySuite/Sunny.jl/issues/110 and performs some additional reorganization.

Allow `set_onsite_coupling!` with zero

---

examples/fei2_tutorial.jl

This removes all classical dynamics from our intro tutorial. Now uses `minimize_energy!` to find the ground state and LSWT for the S(q,omega) calculation.
To-do in a follow up:
- Perform 3-fold rotational averaging to illustrate beautiful agreement with experimental S(q,omega) data.
- Create new tutorials that illustrate the power of classical dynamics (e.g., thermal fluctuations in a spin liquid phase, a quench into CP^2 skyrmions, driven-dissipative dynamics, ...)

Update FeI2 doc

---

docs/src/versions.md
docs/src/writevtk.md
examples/binning_tutorial.jl
examples/fei2_tutorial.jl
examples/longer_examples/CoRh2O4-tutorial.jl
examples/longer_examples/MgCr2O4-tutorial.jl
examples/powder_averaging.jl
src/Optimization.jl
src/Plotting.jl
src/Reshaping.jl
src/SpinWaveTheory/SpinWaveTheory.jl
src/Sunny.jl
src/System/SpinInfo.jl
src/System/System.jl
test/test_binning.jl
test/test_correlation_sampling.jl
test/test_energy_consistency.jl
test/test_jet.jl
test/test_lswt.jl
test/test_optimization.jl
test/test_resize.jl
test/test_samplers.jl
test/test_spin_scaling.jl
test/test_symmetry.jl
test/test_units_scaling.jl

As described in versions.md:
```
Rename `polarize_spin!` to [`set_dipole!`](@ref) for consistency with
[`set_coherent!`](@ref). The behavior of the former function is unchanged: the
spin at a given site will still be polarized along the provided direction.
Rename `reshape_geometry` to [`reshape_supercell`](@ref), which is the
fundamental reshaping function. Rename `resize_periodically` to
[`resize_supercell`](@ref).
The constructor [`SpinInfo`](@ref) now requires a ``g``-factor or tensor as a
named argument.
```

Implement several renamings

---

examples/fei2_tutorial.jl

Updates the text of the FeI2 tutorial and implements averaging over the three symmetry-equivalent orientations.

Orientational averaging

---

docs/src/versions.md
docs/src/writevtk.md
examples/binning_tutorial.jl
examples/longer_examples/CoRh2O4-tutorial.jl
examples/powder_averaging.jl
src/Intensities/Interpolation.jl
src/SampledCorrelations/BasisReduction.jl
src/SampledCorrelations/DataRetrieval.jl
src/SampledCorrelations/FormFactor.jl
src/SampledCorrelations/SampledCorrelations.jl
src/SpinWaveTheory/SWTCalculations.jl
src/SpinWaveTheory/SpinWaveTheory.jl
test/test_correlation_sampling.jl

FormFactor no longer requires an atom index. Instead, the list of FormFactors must appear in the same order as the site symmetry "classes" of the crystal, i.e. as the `crystal.classes` field. The order of these classes is invariant to crystal reshaping.
FormFactors now work for LSWT.
David says this code is on the performance critical path for SampledCorrelations measurements, so we should do a benchmark before merging.

FormFactor update

---

src/SpinWaveTheory/SWTCalculations.jl

@Lazersmoke: Help requested to clarify which units go where. This particular change looks correct given our previous discussions, but I think we need to double check the `q` usage elsewhere.

f in intensity_formula expects absolute units

---

.gitignore
docs/lyx_notes/complex_welford.lyx
src/Intensities/ElementContraction.jl
src/Intensities/Interpolation.jl
src/SampledCorrelations/BasisReduction.jl
src/SampledCorrelations/CorrelationSampling.jl
src/SampledCorrelations/DataRetrieval.jl
src/SampledCorrelations/SampledCorrelations.jl
src/Sunny.jl

The only new thing that this PR publicly exposes is the keyword `calculate_errors` to `dynamical_correlations` and `instant_correlations`. However, I have not documented it because I don't want to make it official yet.
If `calculate_errors` is set to `true`, Sunny will use a modified Welford algorithm to iteratively estimate the complex variance on each matrix element of S(q,w). The exact approach is documented in a lyx file. This variance is recorded into an array called `variance` in `SampledCorrelations`. Its type is `Union{Nothing, Array{Float64, 7}}` and it is only allocated if the keyword is set to true.
The provisional (non-exposed) way to retrieve error estimates is by creating a `error_formula`, which is simply an `intensity_formula` that sets a flag when creating a …

Estimate variance on classical SF calculations

---

src/Intensities/ExperimentData.jl

This needs to happen because Mantid axes labels like `[H,H,0]` (meaning that the coordinate displayed on the axis is `H` and you can compute `Q` from `H` using `Q = [H,H,0]`) are related to the coordinate covectors used by Sunny by a pseudo-inverese (which means transpose and divide by the norm-squared). This way, multiplying (dot product) `[qx,qy,qz]` with `pinv([1,1,0])` gives `(qx+qy)/2`, which is the correct way to extract the label `H` from a vector like `[H,H,0]`.

Invert axes labels when loading from Mantid

---

src/Operators/Stevens.jl
src/SpinWaveTheory/HamiltonianDipole.jl
src/SpinWaveTheory/Util.jl
src/Symmetry/AllowedCouplings.jl
test/test_operators.jl

The implementation passes the check for the scalar biquadratic interactions.
However, a unit test for general interactions still needs to be included. I cannot find a simple general biquadratic interaction compatible with a given symmetry.

Implemented gen-biquad interaction in dipole mode

---

src/SpinWaveTheory/DispersionAndIntensities.jl
src/SpinWaveTheory/HamiltonianDipole.jl
src/SpinWaveTheory/SpinWaveTheory.jl
src/System/Types.jl

A few optimizations for dipole LSWT (starting with removal of allocations associated with biquadratic interactions).

Dipole LSWT Optimizations

---

src/SampledCorrelations/CorrelationSampling.jl
src/SampledCorrelations/SampledCorrelations.jl
test/test_correlation_sampling.jl

Replace running calculation of variance with running calculation of `M=(n-1)*σ²`, where `n` is the number of samples.
The modifications reproduce previous results when `M` is divided by `n-1`. Note that there is currently no interface for retrieving this data. Any future interface will need to divide by `n-1` to recover the variance.

Numerically stable accumulation of intensity variance

---

src/SampledCorrelations/CorrelationUtils.jl
src/SampledCorrelations/SampledCorrelations.jl

This is a fix for the `available_energies` function, which was previously handling negative energies incorrectly. @Lazersmoke identified the problem and suggested the solution.

Fix `available_energies`

---

docs/src/versions.md
examples/03_LLD_CoRh2O4.jl
examples/04_GSD_FeI2.jl
src/Integrators.jl
src/OnlineStatistics.jl
src/Sunny.jl

Collect statistics from numerical integration to provide suggestions about the choice of dt.

Suggest integration timestep

---

src/Integrators.jl

Small damping can lead the large statistical error, and the user should be guided towards ImplicitMidpoint for now.

Add checks on Langevin parameters

---

src/System/System.jl

Now that `energy(sys)` sometimes errors (e.g. if dipoles are not normalized), typing in `sys` at the REPL can clobber the terminal with a huge error message. This PR makes it so the error message is relatively tame

Catch errors during show(System)

---

docs/src/parallelism.md
docs/src/structure-factor.md
docs/src/versions.md
docs/src/writevtk.md
examples/03_LLD_CoRh2O4.jl
examples/04_GSD_FeI2.jl
examples/06_CP2_Skyrmions.jl
examples/extra/heisenberg_animation.jl
ext/PlottingExt.jl
src/Integrators.jl
src/SampledCorrelations/CorrelationSampling.jl
src/SampledCorrelations/SampledCorrelations.jl
src/System/PairExchange.jl
src/deprecated.jl
test/test_binning.jl
test/test_correlation_sampling.jl
test/test_energy_consistency.jl
test/test_jet.jl
test/test_optimization.jl
test/test_rescaling.jl
test/test_samplers.jl

Replace keyword arguments:
* `Δt` with `dt`
* `λ` with `damping`
Using the old symbols will emit a deprecation warning, and will break in 0.6.

Remove most unicode from public API

---

docs/src/versions.md
ext/PlottingExt.jl
src/Symmetry/SymOp.jl
src/System/OnsiteCoupling.jl
src/System/PairExchange.jl
src/deprecated.jl
test/test_rescaling.jl

Support a `biquad` parameter in `set_exchange!` to allow scalar biquadratic interactions for the special case of mode `:dipole_large_S`. The original plan was to avoid this, and instead use DynamicPolynomials to represent arbitrary biquadratic couplings symbolically. It's not clear whether the complexity of a full symbolic treatment justifies the benefit. We should be guiding people towards `:dipole` mode instead, which performs physically correct renormalizations. Nonetheless, scalar biquadratic interactions in `:dipole_large_S` can still be important for reproducing SpinW studies.
Resolves https://github.com/SunnySuite/Sunny.jl/issues/251.

Scalar biquadratic support for `:dipole_large_S`

---

src/Intensities/ElementContraction.jl
test/test_intensities_setup.jl

Also now enables element contractor for spin wave theory, and brings the formatting in line with the other contractors

Bugfix: typo in `Element` contractor

---

docs/src/versions.md
src/MathBasics.jl
src/SpinWaveTheory/DispersionAndIntensities.jl
src/SpinWaveTheory/HamiltonianDipole.jl
src/SpinWaveTheory/SpinWaveTheory.jl
src/System/OnsiteCoupling.jl
src/System/PairExchange.jl
src/System/System.jl
test/test_lswt.jl

This fixes two bugs:
1. Indexing in `spin_label` was previously incorrect.
2. LSWT in dipole mode was using the first spin as representative of all spins.

Support varying spin-S in dipole mode

---

docs/src/versions.md
src/Intensities/ExperimentData.jl

This is required for the Shiver script, which can place the axes in any order (not just space,space,space,energy).
Also adds `permutedims` instance for `BinningParameters`, since some Sunny functions will expect you to be in the canonical space,space,space,energy order.

Support more complicated `.nxs` in `load_nxs`

---

src/System/PairExchange.jl
src/deprecated.jl
test/test_rescaling.jl

Since scalar-biquadratic is such a common use case, this PR uniformly supports again it with the `biquad` argument to `set_exchange!`, regardless of mode.
I was originally hoping we could entirely remove the `biquad` argument, and instead direct people to the more general `set_pair_coupling!` function. That idea hit a snag with `mode = :dipole_large_S`. In particular, Sunny doesn't have a way to represent symbolic spin operators ($S \to \infty$) in the tensor product space along a bond. It would be complicated to implement, and there is not a strong motivation, especially since we are de-emphasizing `:dipole_large_S`.
Fixes #276.

Undeprecate `biquad` argument in `set_exchange!`

---

test/test_correlation_sampling.jl

This simplification makes it pass on both 1.11 and 1.10.

Simplify sampled correlations test

---

docs/src/versions.md
examples/05_MC_Ising.jl
examples/06_CP2_Skyrmions.jl
examples/08_Momentum_Conventions.jl
examples/extra/Advanced_MC/PT_WHAM_ising2d.jl
examples/extra/Advanced_MC/REWL_ising2d.jl
examples/extra/Advanced_MC/WL_ising2d.jl
ext/PlottingExt.jl
src/MCIF.jl
src/Spiral/SpiralEnergy.jl
src/System/Ewald.jl
src/System/Interactions.jl
src/System/System.jl
src/Units.jl
test/test_chirality.jl
test/test_ewald.jl
test/test_lswt.jl
test/test_spiral.jl
test/test_units_scaling.jl

* Ensure that the Bohr magneton $μ_B$ is positive, even with "theory" units. To include a Zeeman coupling of the form $- S ⋅ B$, it is now required to select negative `g = -1` in addition to selecting `Units.theory`.
* Disallow dipole-dipole interactions with `Units.theory` -- such an interaction doesn't make sense once the energy and length scale units become ambiguous.
* Modify `magnetic_moment` so that its return value is in units of $μ_B$.

Change Units.theory conventions

---

docs/src/versions.md
examples/spinw_tutorials/SW03_Frustrated_chain.jl
examples/spinw_tutorials/SW08_sqrt3_kagome_AFM.jl
examples/spinw_tutorials/SW15_Ba3NbFe3Si2O14.jl
examples/spinw_tutorials/SW18_Distorted_kagome.jl
src/MagneticOrdering.jl
src/Reshaping.jl
src/Spiral/SpiralEnergy.jl
src/Spiral/SpiralSWT.jl
src/Sunny.jl
src/System/PairExchange.jl
src/deprecated.jl
test/test_chirality.jl
test/test_lswt.jl
test/test_spiral.jl

This deprecates `set_spiral_order_on_sublattice!` and `set_spiral_order!`.

Add `repeat_periodically_as_spiral`

---

examples/04_GSD_FeI2.jl
src/SampledCorrelations/DataRetrieval.jl

Adds an error message when a user sets `kT=0` when calling `intensities` on a `SampledCorrelations`. Somewhat simplifies the set of conditionals that check whether an `intensities` call is valid for a given `SampledCorrelations`.

Error message when calling intensities on a SC with `kT=0`

---

examples/02_LSWT_CoRh2O4.jl
examples/03_LLD_CoRh2O4.jl
examples/07_Dipole_Dipole.jl
examples/08_Momentum_Conventions.jl
examples/spinw_tutorials/SW11_La2CuO4.jl
examples/spinw_tutorials/SW12_Triangular_easy_plane.jl
examples/spinw_tutorials/SW13_LiNiPO4.jl
examples/spinw_tutorials/SW14_YVO3.jl
examples/spinw_tutorials/SW18_Distorted_kagome.jl
examples/spinw_tutorials/SW19_Different_Ions.jl

Original ports by Bhushan Thipe.

Add SpinW tutorials 12, 13, 14

---

src/SampledCorrelations/DataRetrieval.jl
src/SpinWaveTheory/DispersionAndIntensities.jl

Clarify some of the logic around `SampledCorrelations`.
Also, `thermal_prefactor` now correctly goes to 1/2 when ω = kT = 0.

Small cleanups to SampledCorrelations

---

docs/make.jl
docs/src/renormalization.md
docs/src/structure-factor.md
docs/src/versions.md
examples/01_LSWT_CoRh2O4.jl
examples/02_LLD_CoRh2O4.jl
examples/04_GSD_FeI2.jl
examples/08_Momentum_Conventions.jl
examples/spinw_tutorials/SW12_Triangular_easy_plane.jl
examples/spinw_tutorials/SW13_LiNiPO4.jl
examples/spinw_tutorials/SW14_YVO3.jl
examples/spinw_tutorials/SW19_Different_Ions.jl
src/FormFactor.jl
src/KPM/SpinWaveTheoryKPM.jl
src/Measurements/MeasureSpec.jl
src/Measurements/RotationalAverages.jl
src/Operators/Spin.jl
src/Operators/Stevens.jl
src/SampledCorrelations/DataRetrieval.jl
src/SpinWaveTheory/DispersionAndIntensities.jl
src/SpinWaveTheory/SpinWaveTheory.jl
src/Spiral/SpiralSWT.jl
src/System/Moment.jl
src/System/PairExchange.jl
src/System/System.jl
test/test_chirality.jl
test/test_correlation_sampling.jl
test/test_kpm.jl
test/test_lswt.jl
test/test_rescaling.jl

The new syntax is:
```julia
formfactors = [1 => FormFactor("Fe2"), 2 => FormFactor("Cu2")]
measure = ssf_perp(sys; formfactors)
```
Including explicit atom indices is required to eventually support non-isotropic form factors. Also, this PR lays the foundations for observable-dependent form factors. For example, with an appropriate superposition of pair measurements, it should eventually be possible to allow form factors to vary correctly in an inhomogeneous system.

Move `formfactors` into `measure`

---

docs/src/structure-factor.md
docs/src/versions.md
examples/spinw_tutorials/SW03_Frustrated_chain.jl
examples/spinw_tutorials/SW08_sqrt3_kagome_AFM.jl
examples/spinw_tutorials/SW15_Ba3NbFe3Si2O14.jl
examples/spinw_tutorials/SW18_Distorted_kagome.jl
src/Reshaping.jl
src/SpinWaveTheory/DispersionAndIntensities.jl
src/SpinWaveTheory/SpinWaveTheory.jl
src/Spiral/SpinWaveTheorySpiral.jl
src/Spiral/SpiralEnergy.jl
src/Sunny.jl
test/test_chirality.jl
test/test_spiral.jl

Rename `SpiralSpinWaveTheory`  → `SpinWaveTheorySpiral` in consistency with `SpinWaveTheoryKPM`.
Rename `spiral_minimize_energy!` → `minimize_spiral_energy!` for readability, and to aid discoverability with respect to `minimize_energy!`.

Spiral renamings

---

examples/01_LSWT_CoRh2O4.jl
examples/03_LSWT_SU3_FeI2.jl
examples/04_GSD_FeI2.jl
examples/06_CP2_Skyrmions.jl
examples/07_Dipole_Dipole.jl
examples/08_Momentum_Conventions.jl
examples/extra/Plotting/plotting2d.jl
examples/spinw_tutorials/SW01_FM_Heseinberg_chain.jl
examples/spinw_tutorials/SW05_Simple_kagome_FM.jl
examples/spinw_tutorials/SW08_sqrt3_kagome_AFM.jl
examples/spinw_tutorials/SW15_Ba3NbFe3Si2O14.jl
examples/spinw_tutorials/SW18_Distorted_kagome.jl
examples/spinw_tutorials/SW19_Different_Ions.jl
src/Measurements/Broadening.jl
src/Measurements/MeasureSpec.jl
src/SampledCorrelations/SampledCorrelations.jl
src/SpinWaveTheory/SpinWaveTheory.jl

Also fixing indexing error in `get_swt_formfactor`.

Docs fine tuning

---

examples/01_LSWT_CoRh2O4.jl
examples/02_LLD_CoRh2O4.jl
examples/03_LSWT_SU3_FeI2.jl
examples/04_GSD_FeI2.jl
examples/07_Dipole_Dipole.jl
examples/08_Momentum_Conventions.jl
examples/spinw_tutorials/SW08_sqrt3_kagome_AFM.jl
examples/spinw_tutorials/SW15_Ba3NbFe3Si2O14.jl
examples/spinw_tutorials/SW19_Different_Ions.jl
ext/PlottingExt.jl

* Include color bar when plotting intensity heatmap.
* Add `title` keyword argument to easily label intensity plots.
* Hide `axisopts` while we consider UI alternatives.

Colorbars and titles

---

docs/src/versions.md
src/System/PairExchange.jl
test/test_rescaling.jl

Relevant when `biquad` argument is passed to `set_exchange!`. The more general `set_pair_coupling!` remains correct.

Fix scalar biquadratic interaction

---

docs/src/versions.md
src/SampledCorrelations/DataRetrieval.jl
test/test_correlation_sampling.jl

Fixes the bug reported by Yishu Wang which is triggered when the requesting intensities at successive q points that reference the same underlying data in the `data` field of `SampledCorrelations`.
Previously, wave vectors such as `[0, 0, 1/2]` and `[1, 0, 1/2]` were falsely identified when they appeared successively. This led to incorrect treatment of phase averaging and form factors.

Fix test for repeated wave vectors in SampledCorrelations

---

docs/src/versions.md
ext/PlottingExt.jl

Fix subtle problems associated with the Colorbar used in `plot_intensities`. These problems arose primarily when all intensities were very close to zero, with small numerical roundoff, such that the suggested `colorrange` pair was non-ascending. This PR adds logic to ensure that the suggested `colorrange` is always strictly ascending. For the special case of uniformly zero intensity, the selected color will correspond to the low end of the `colorrange`.

Make Colorbar more reliable

---

docs/src/versions.md
examples/01_LSWT_CoRh2O4.jl
examples/09_Disorder_KPM.jl
examples/09_Disordered_spectrum.jl
examples/spinw_tutorials/SW02_AFM_Heisenberg_chain.jl
examples/spinw_tutorials/SW03_Frustrated_chain.jl
examples/spinw_tutorials/SW04_Frustrated_square.jl
src/KPM/Chebyshev.jl
src/KPM/Lanczos.jl
src/KPM/SpinWaveTheoryKPM.jl
src/Measurements/Broadening.jl
src/SpinWaveTheory/DispersionAndIntensities.jl
src/Sunny.jl
test/test_kpm.jl

The new interface automatically selects the polynomial order according to the specified error tolerance. If `tol` is too high, some ringing will become visible. This is a sign that `tol` must be lowered.
In spite of the name "kernel polynomial method" (KPM), this implementation does not employ a Jackson kernel. Instead, we use simple truncation of the Chebyshev series (i.e., the "Dirichlet kernel"). For purposes of approximating relatively _smooth_ functions, this simple truncation provides accuracy that improves exponentially with the number of polynomials, `M ~ -log(tol)`.
The finite temperature Bose occupation factor has been removed for now because I haven't been able to find a good regularization strategy. At $T=0$, the Bose occupation factor becomes a step function at $\omega = 0$, …

Stabilize KPM

---

src/System/OnsiteCoupling.jl

Quantum mechanics disallows single-ion anisotropy for quantum spin-1/2. This is because any Pauli matrix squared is the identity matrix. Sunny follows quantum mechanics, but it can be confusing to users who may be thinking of spins as classical dipole vectors. Print an informative error message if this situation is detected, and provide guidance about using `:dipole_large_s` to reproduce legacy calculations.

Warn if `set_onsite_coupling!` is called for spin `s=1/2`

---

docs/src/versions.md
ext/PlottingExt.jl
src/Binning/Binning.jl
src/Binning/ExperimentData.jl
src/Sunny.jl
test/test_binning.jl

In Sunny v0.7, there are `QGrid{2}`s and `QPath`s. These each contain slightly less information than is needed to fully specify the regions of Q-space which the data comes from. In particular, you can have multiple transverse binning configurations (blue box, orange box) which are centered on exactly the same `QPath` (red Xs), see image:
This PR adds `specify_transverse_binning` which "upgrades" a `QGrid{2}` or `QPath` into the corresponding `BinningParameters`, taking the extra information about the transverse binning as input. This function should be used in conjunction with `integrate_axes!` and `energy_resolve!` to further add energy-binning information or to integrate out unneeded axes.
It also adds `binned_intensities`, which does the following:
1. It decides which of the …

0.7-style binning

---

src/SampledCorrelations/DataRetrieval.jl
src/SampledCorrelations/PhaseAveraging.jl

Removed the `MVector` from the phase averaging procedure and replaced with an `SVector`. This explicitly ensures static behavior without relying on compiler optimizations. On a simple example, performance was improved by ~35%.

Remove `MVector` from intensities calls for `SampledCorrelations`

---

src/Symmetry/Crystal.jl
src/Symmetry/LatticeUtils.jl
src/Symmetry/WyckoffData.jl
test/test_symmetry.jl

Test that the correct Wyckoff can be inferred from a spacegroup number and position coordinates. This is a bit subtle because it requires searching over a range of possible integer offsets.

Add Wyckoff inference test

---

docs/make.jl
docs/src/parallelism.md
docs/src/versions.md
examples/02_LLD_CoRh2O4.jl
examples/03_LSWT_SU3_FeI2.jl
examples/05_MC_Ising.jl
examples/07_Dipole_Dipole.jl
examples/spinw_tutorials/SW10_Energy_cut.jl
examples/spinw_tutorials/SW15_Ba3NbFe3Si2O14.jl
examples/spinw_tutorials/SW18_Distorted_kagome.jl
examples/spinw_tutorials/SW19_Different_Ions.jl
src/System/System.jl

The default `System` random number seed is now `seed=rand(UInt)`. The motivation is that calling `Random.seed!` prior to `System` construction will fix `System.rng` in a deterministic way. This may be helpful for writing reproducible Sunny scripts that sometimes _also_ call Julia's task-local RNG.
An underlying motivation is to make the doc builds exactly reproducible. This will hopefully allow for more compression on the `gh-pages` branch, which already requires 160+ MB to store docs images, with repetition on every Sunny release. See also https://github.com/SunnySuite/Sunny.jl/issues/233#issuecomment-2476980802.

Default seed for a `System` is generated from the task-local RNG

---

README.md
docs/make.jl
docs/src/index.md
docs/src/library.md
docs/src/renormalization.md
docs/src/structure-factor.md
docs/src/why.md
src/Spiral/SpiralEnergy.jl

The docs landing page better describes what Sunny is, and provides links to its various features.
Within the Library Reference page, URLs for function docstrings now omit type information.

Update the documentation landing page

---

Project.toml
ext/GLMakiePrecompilesExt.jl

The extension module GLMakiePrecompilesExt aims to precompile plotting functions for the GLMakie backend. The plotting functions themselves, however, are defined in a different extension module, PlottingExt, which is agnostic to Makie backend. This setup accidentally broke in Julia 1.11.1, which disallowed dependencies between extension modules. Hopefully there will be a solution in Julia 1.11.2, as per https://github.com/JuliaLang/julia/issues/56204#issuecomment-2442652997.
This PR makes the dependencies of GLMakiePrecompilesExt a strict superset of the dependencies of PlottingExt, so that it is safe to make GLMakiePrecompilesExt depend on PlottingExt. Enabled by https://github.com/JuliaLang/julia/pull/56368, which has now been backported to 1.11.

Support GLMakie precompiles on Julia 1.11.2

---

src/Spiral/LuttingerTisza.jl

Luttinger-Tisza support is not public nor well tested. But this PR avoids a crash when using LT with Ewald for long-range dipole-dipole interactions.

Fix Ewald couplings within Luttinger-Tisza analysis

---

Project.toml
docs/src/versions.md
src/Operators/Rotation.jl
src/Optimization.jl
src/SpinWaveTheory/HamiltonianDipole.jl
src/SpinWaveTheory/SpinWaveTheory.jl
src/System/Interactions.jl
src/System/OnsiteCoupling.jl
src/System/PairExchange.jl
test/shared.jl
test/test_energy_consistency.jl

Make linear spin wave theory compatible with `set_vacancy_at!`. To simplify the indexing of a system, vacant sites are not truly removed. However, they are marked as non-magnetic with `iszero(sys.κs[site])`. When LSWT detects this case, all operators on the vacant site will be set to zero. Consequently, bosons on vacant sites will not be excited, and do not contribute to any intensities. Note, however, that vacant sites will still produce artificial zero-energy bands that must be ignored.

Support vacancies in spin wave theory

---

docs/src/versions.md
src/MagneticOrdering.jl
test/test_resize.jl

With this fix, `suggest_magnetic_supercell([1/2, 0, 0], [0, 1/2, 0])` correctly reports `[2 0 0; 0 2 0; 0 0 1]`.

Fix `suggest_magnetic_supercell` with multiple wavevectors

---

docs/src/structure-factor.md
docs/src/versions.md
docs/src/why.md
examples/09_Disorder_KPM.jl
src/KPM/Lanczos.jl
src/KPM/SpinWaveTheoryKPM.jl
src/SpinWaveTheory/DispersionAndIntensities.jl
src/SpinWaveTheory/HamiltonianDipole.jl
test/test_kpm.jl

The Lanczos algorithm promises these benefits relative to KPM:
- Higher accuracy at a fixed number of iterations (i.e., at a fixed Krylov subspace dimension).
- Does not require an initialization phase that bounds the spectrum prior to polynomial expansion.
- Ability to detect instabilities (negative eigenvalues) in the dynamical matrix.
- Allows for a sharp cutoff between positive and negative eigenvalues near zero. ~~Whereas KPM is susceptible to a loss of intensity near Goldstone modes, Lanczos seems to avoid this problem.~~ (Unfortunately, despite my initial hopes, intensity is still lost via various mechanisms. See examples below.)
As currently implemented, Lanczos is slower than KPM _per iteration_. But fewer iterations are required, so Lanczos still seems favorable in overall …

Replace KPM with Lanczos

---

src/Reshaping.jl

Clone `sys.origin` when building reshaped system

---

ext/PlottingExt/ViewCrystal.jl
src/Operators/Stevens.jl
src/Reshaping.jl
src/System/OnsiteCoupling.jl
src/System/PairExchange.jl
test/test_interaction_setup.jl
test/test_rescaling.jl
test/test_symmetry.jl

Add `get_exchange`, `get_quadratic_anisotropy`, and related variants for inhomogeneous systems. We can wait for user-experience reports before adding them to the public API.
The functionality is exercised with this new test:
```jl
@testitem "Interaction lookup" begin
using LinearAlgebra
latvecs = lattice_vectors(1, 1, 1, 90, 90, 90)
positions = [[0, 0, 0], [0.5, 0.5, 0.5]]
cryst = Crystal(latvecs, positions, 1)
function run_test(mode)
sys = System(cryst, [1 => Moment(s=1, g=2), 2 => Moment(s=1, g=2)], mode)
randomize_spins!(sys)
D1 = hermitianpart(randn(3, 3))
D2 = hermitianpart(randn(3, 3))
set_onsite_coupling!(sys, S -> S'*D1*S, 1)
set_onsite_coupling!(sys, S -> S'*D2*S, 2)
sys2 = reshape_supercell(sys, [1 1 0; 0 2 0; 0 0 1])
@test energy_per_site(sys) ≈ energy_per_site(sys2)
@test …
```

Functions to look up quadratic interactions from a system

---

src/EntangledUnits/EntangledSampledCorrelations.jl
src/Integrators.jl
src/SampledCorrelations/CorrelationSampling.jl
src/SampledCorrelations/SampledCorrelations.jl
src/System/Interactions.jl
test/test_intensities_setup.jl
test/test_rescaling.jl

This PR allows the user to specify an integrator other than an `ImplicitMidpoint` when creating a `SampledCorrelations`. This allows the use of dissipative dynamics when creating sample trajectories.
The change is motivated by Joe Paddison's request for Langevin dynamics with longitudinal fluctuations.

Allow custom integrator in SampledCorrelations

---

src/Symmetry/Printing.jl

Clean `print_site` if allowed anisotropy operators are missing

---

docs/src/versions.md
examples/03_LSWT_SU3_FeI2.jl
examples/04_GSD_FeI2.jl
examples/08_Momentum_Conventions.jl
examples/spinw_tutorials/SW01_FM_Heseinberg_chain.jl
examples/spinw_tutorials/SW02_AFM_Heisenberg_chain.jl
examples/spinw_tutorials/SW08_sqrt3_kagome_AFM.jl
examples/spinw_tutorials/SW11_La2CuO4.jl
examples/spinw_tutorials/SW18_Distorted_kagome.jl
ext/PlottingExt/PlotIntensities.jl
src/Measurements/IntensitiesTypes.jl
src/Measurements/QPoints.jl
src/Measurements/RotationalAverages.jl

Allow to call `intensities_static` from within `powder_average`. For example:
```jl
using Sunny, GLMakie
units = Units(:meV, :angstrom)
a = 8.5031 # (Å)
latvecs = lattice_vectors(a, a, a, 90, 90, 90)
cryst = Crystal(latvecs, [[1/8, 1/8, 1/8]], 227)
sys = System(cryst, [1 => Moment(s=3/2, g=2)], :dipole)
J = 0.63 # (meV)
set_exchange!(sys, J, Bond(2, 3, [0, 0, 0]))
kT = 16*units.K
sys2 = repeat_periodically(sys, (10, 10, 10))
measure = ssf_trace(sys2)
sc = SampledCorrelationsStatic(sys2; measure)
langevin = Langevin(0.04; damping=0.2, kT)
for _ in 1:1000
step!(sys2, langevin)
end
for _ in 1:100
for _ in 1:100
step!(sys2, langevin)
end
add_sample!(sc, sys2)
end
radii = range(0, 10, 200) # (1/Å)
res = powder_average(cryst, radii, 400) do qs
intensities_static(sc, qs)
end …
```

Powder averaging of static intensities

---

Project.toml
docs/src/library.md
docs/src/versions.md
src/EntangledUnits/EntangledSpinWaveTheory.jl
src/SCGA/NewtonBacktracking.jl
src/SCGA/SCGA.jl
src/SCGA/StaticCorrelationsSCGA.jl
src/SpinWaveTheory/DispersionAndIntensities.jl
src/SpinWaveTheory/SpinWaveTheory.jl
src/Spiral/LuttingerTisza.jl
src/Spiral/SpinWaveTheorySpiral.jl
src/Spiral/SpiralEnergy.jl
src/Sunny.jl
src/System/System.jl
test/test_scga.jl
test/test_spiral.jl

Takes inspiration from [Spinteract](https://arxiv.org/abs/2210.09016) and [JuliaSCGA](https://github.com/moon-dust/JuliaSCGA.jl). However, this implementation is unique in that it allows for a distinct sum-rule constraint on each symmetry-inequivalent sublattice. It turns out that we can determine the Lagrange multipliers by _maximizing_ the appropriate free energy as worked out in the attached note:
[SCGA-notes.lyx.zip](https://github.com/user-attachments/files/19985137/SCGA-notes.lyx.zip)
[SCGA-notes.pdf](https://github.com/user-attachments/files/19985141/SCGA-notes.pdf)
We use a custom implementation of Newton-Raphson with backtracking using an Armijo condition. Optim's implementation of Newton-Raphson method uses line search, which requires more overall iterations and provides less …

Self-consistent Gaussian Approximation (SCGA)

---

ext/PlottingExt/PlotIntensities.jl

The name `axis` for a dict-like set of `Makie.Axis` configuration options is consistent with Makie conventions:
https://docs.makie.org/v0.22/explanations/plot_method_signatures#Special-Keyword-Arguments
The argument `axisopt` was hidden and not used in any of the tutorials, so this change seems to be non-breaking.

Rename hidden `axisopt` keyword argument to `axis`

---

docs/src/versions.md
examples/07_Dipole_Dipole.jl
ext/PlottingExt/PlotIntensities.jl

A very large grid passed to `Makie.image` or `Makie.heatmap` causes certain OpenGL backends to fail. Consequently, `plot_intensities` will not render certain data.
As discussed in https://github.com/MakieOrg/Makie.jl/issues/4950, a workaround is to convert all uses of `Makie.image` to `Makie.heatmap`, and then wrap the grid data inside a `Makie.Resampler` object. That is implemented here.
Notes:
* Apart from this bug, `Makie.image` could be preferable over `Makie.heatmap` in other ways, e.g., data on a regular grid is faster to render. However, the two have some subtle rendering differences: axis ranges may change slightly, and `heatmap` does not interpolate between grid points like `image` seems to.
* No attempt is made to determine what grid sizes will cause rendering to fail for the …

Fix `plot_intensities` for data on very large grids

---

docs/src/versions.md
examples/07_Dipole_Dipole.jl
src/Reshaping.jl
src/SpinWaveTheory/HamiltonianDipole.jl
src/SpinWaveTheory/HamiltonianSUN.jl
src/Spiral/LuttingerTisza.jl
src/Spiral/SpinWaveTheorySpiral.jl
src/Spiral/SpiralEnergy.jl
src/System/Ewald.jl
src/System/Interactions.jl
src/System/System.jl
src/System/Types.jl
test/test_ewald.jl
test/test_lswt.jl
test/test_units.jl

Extend `enable_dipole_dipole!` to accept an additional parameter `demag`. It defines the demagnetization factor tensor associated with the geometry of the macroscopic sample. The new default, `demag = 1/3`, is appropriate for a spherical sample in vacuum. More generally, `demag` can be an arbitrary 3×3 matrix, typically with trace 1.
Demagnetization originates through surface effects at the sample boundary. These are traditionally neglected in the Ewald summation method. The necessary correction was derived in S. W. DeLeeuw et al., Proc. R. Soc. Lond. A 373, 27-56 (1980). See  [Ballenegger, J. Chem. Phys. 140, 161102 (2014)](https://pubs.aip.org/aip/jcp/article/140/16/161102/841086/Communication-On-the-origin-of-the-surface-term-in) for a pedagogical review.
Fixes #380.

Dipole-dipole interactions incorporate demagnetization factor tensor

---

src/EntangledUnits/EntangledSampledCorrelations.jl
test/test_entangled_units.jl

Fix for the constructor of `SampledCorrelationsStatic` for entangled systems. I neglected to update this when putting the integrator (instead of dt) into the `SampledCorrelations` type.
Also added is a simple test using `SampledCorrelationsStatic` in the test suite (which would have revealed this problem).
Ultimately this code duplication should be avoidable.

Entangled units fix

---

docs/src/versions.md
docs/src/why.md
src/MCIF.jl
src/MathBasics.jl
src/Reshaping.jl
src/SpinWaveTheory/SpinWaveTheory.jl
src/Symmetry/Crystal.jl
src/Symmetry/Parsing.jl
src/Symmetry/Printing.jl
src/Symmetry/SpacegroupData.jl
src/Symmetry/SymOp.jl
src/Symmetry/SymmetryAnalysis.jl
src/Symmetry/WyckoffData.jl
test/cifs/FeI2_orth.cif
test/cifs/UPt3.cif
test/cifs/alpha_quartz.cif
test/test_cif.jl
test/test_symmetry.jl

More robust loading of CIF files. Dimensionless precision `symprec` is now inferred. Loading an mCIF file will automatically convert to a standard chemical cell compatible with `set_dipoles_from_mcif!`. Various other internal robustness improvements. Fixes #409 and #225.

Improvements to CIF and mCIF loading
